repos:
  - repo: local
    hooks:
      - id: prebuild
        name: prebuild
        stages: [pre-commit]
        language: system
        entry: make build
        pass_filenames: false
        files: ".*"

      - id: vhdl_parser
        name: vhdl_parser
        stages: [pre-commit]
        language: system
        entry: make vhdl_parser
        pass_filenames: false
        files: "^redhdl/parser/"

      - id: lint
        name: lint
        stages: [pre-commit]
        language: system
        entry: make lint
        types: [python]
        pass_filenames: false
        files: ".*"

      - id: test
        name: test
        stages: [pre-commit]
        language: system
        entry: make test
        types: [python]
        pass_filenames: false
        files: ".*"
