repos:
  - repo: local
    hooks:
      - id: vhdl_parser
        name: vhdl_parser
        stages: [commit]
        language: system
        entry: make vhdl_parser
        types: [python]
        pass_filenames: false
        files: "^redhdl/parser/"

      - id: lint
        name: lint
        stages: [commit]
        language: system
        entry: make lint
        types: [python]
        pass_filenames: true
        files: "^redhdl/"

      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: mypy
        types: [python]
        pass_filenames: true
        files: "^redhdl/"

      - id: pytest
        name: pytest
        stages: [commit]
        language: system
        entry: pytest --suppress-no-test-exit-code
        types: [python]
        files: "^redhdl/"
