[tool.black]
extend-exclude = '''
^.*/(ascii_dag|autogen|vhdlLexer.py|vhdlParser.py|vhdlParserVisitor.py|vhdlParserListener.py)$
'''

[tool.isort]
profile = "black"
atomic = true
force_sort_within_sections = true
multi_line_output = 3
known_first_party = [
    "redhdl",
]

skip = [
    "redhdl/ascii_dag.py",
    "redhdl/parser/autogen",
    "redhdl/parser/vhdlLexer.py",
    "redhdl/parser/vhdlParser.py",
    "redhdl/parser/vhdlParserVisitor.py",
    "redhdl/parser/vhdlParserListener.py",
]

[tool.mypy]
files = "redhdl"
ignore_missing_imports = true
exclude = "ascii_dag.py|vhdl(Lexer|Parser|Listener|ParserVisitor|Visitor|ParserListener).py"

[tool.pytest.ini_options]
addopts = "--doctest-modules --ignore=redhdl/parser/autogen --ignore=redhdl/parser/vhdlLexer.py --ignore=redhdl/parser/vhdlParser.py --ignore=redhdl/parser/vhdlParserVisitor.py"
doctest_optionflags = "ELLIPSIS"
filterwarnings = "ignore::DeprecationWarning"

[tool.pydocstyle]
match-dir = "(?!parser)(?!\\.).*"
match = "(?!test_)(?!ascii_dag).*\\.py"