#!/usr/bin/env python

from argparse import ArgumentParser
from glob import glob
from random import seed
from re import match
from string import ascii_uppercase
from subprocess import run

from redhdl.assembly.assembly import assembled_circuit_schem
from redhdl.netlist.schematic_instance import schematic_instance_from_schem
from redhdl.netlist.vhdl_netlist import (
    netlist_template_from_vhdl_path,
    vhdl_stub_from_instance,
)
from redhdl.voxel.schematic import display_schematic, load_schem, save_schem

def _camel_case(value: str) -> str:
    return "_".join(
        ((part[0].upper() + part[1:]) if part else "")
        for part in value.split("_")
    )


def regenerate_stub_file():
    stub_path = f"build/stubs.sv"
    stub_strs = []
    for schem_path in glob("schematics/*.schem"):
        schem_name, = match("schematics/(.+)\\.schem", schem_path).groups()
        try:
            schem_instance = schematic_instance_from_schem(load_schem(schem_path))
            stub_strs.append(vhdl_stub_from_instance(schem_instance, schem_name))
        except BaseException as e:
            print(f"Failed to load {schem_path}: {e}")


    with open(stub_path, "w") as f:
        f.write(
            "// THIS STUBS IS AUTOGENERATED FROM SCHEMATIC FILES. "
            + "IT WILL BE OVERWRITTEN AUTOMATICALLY.\n"
            + "// DO NOT EDIT THIS FILE DIRECTLY.\n\n"
            + "\n\n".join(
                f"// ==[ Module stub for {schem_name} ]==\n"
                + stub_str
                for stub_str in stub_strs
            )
        )


def assemble_module(module_name: str):

    seed(1337)

    vhdl_path = f"build/{module_name}.vhdl"
    sv_to_vhdl_command_parts = [
        "iverilog",
        "-g2012",
        "-tvhdl",
        f"-s{_camel_case(module_name)}",
        f"-o{vhdl_path}",
        "-y modules/",
        f"modules/{_camel_case(module_name)}.sv",
        "build/stubs.sv",
    ]
    result = run(sv_to_vhdl_command_parts)
    if result.returncode != 0:
        raise RuntimeError(
            "Failed to translate generic SystemsVerilog to simple VHDL;\n"
            + f"command `{' '.join(sv_to_vhdl_command_parts)}` returned "
            + f"nonzero exit code {result.returncode}."
        )

    instance_configs, port_slice_assignments = (
        netlist_template_from_vhdl_path(vhdl_path, module_name)
    )

    print(f"Assembling {module_name}")
    schem = assembled_circuit_schem(
        instance_configs,
        port_slice_assignments,
    )

    schem_path = f"{module_name}.schem"
    print(f"Saving to {schem_path}.")
    save_schem(schem, schem_path)


def arg_parser() -> ArgumentParser:
    parser = ArgumentParser(
        description="Synthesize redstone circuitry from SystemsVerilog modules.",
    )
    parser.add_argument(
        "module_name",
        help="the root SV module to compile"
    )
    parser.add_argument(
        "--list-modules",
        help="list the available modules",
    )
    return parser


def main():
    args = arg_parser().parse_args()

    regenerate_stub_file()
    assemble_module(args.module_name)



if __name__ == "__main__":
    main()
